name: CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install libomp
          fi
      
      - name: Configure CMake
        run: cmake -S . -B build
      
      - name: Build
        run: cmake --build build --parallel
      
      - name: Run ops tests
        run: ./build/tests/test_ops