name: CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

jobs:
  test:
    strategy:
      matrix:
      # slightly cleaner than force install
        include:
          - os: ubuntu-latest
            container: gcc:14
          - os: macos-latest
            container: null
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    
    steps:
      - uses: actions/checkout@v5
      - name: Configure CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build --parallel
      - name: Run ops tests
        run: ./build/test_ops_runner