on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      - name: Test compilation
        run: make compile-test

  unit-tests:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v5
      - name: Run unit tests
        run: make unit-tests