name: CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      
      # weird issue with cosf, sinf, etc. not being in the std:: namespace
      # for GCC < 14
      - name: Install GCC 14 (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100

      - name: Configure CMake
        run: cmake -B build
      
      - name: Build
        run: cmake --build build --parallel
      
      - name: Run ops tests
        run: ./build/test_ops_runner