name: CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: gcc:14
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || null }}
    
    steps:
      - uses: actions/checkout@v5
      - name: Install CMake (Linux)
        if: matrix.container == 'gcc:14'
        run: apt update && apt install -y cmake
      - name: Configure CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build --parallel
      - name: Run ops tests
        run: ./build/test_ops_runner